global using Carter;
global using MediatR;
global using TripPlanningService.Application.CQRS.Commands.DayCommands;
global using TripPlanningService.Application.CQRS.Commands.TripCommands;
global using TripPlanningService.Application.CQRS.Queries.TripQueries;
global using TripPlanningService.Application.DTOs.TripDayDTOs;
global using TripPlanningService.Domain.Exceptions;
global using TripPlanningService.Application.DTOs.ActivityDTOs;
global using TripPlanningService.Application.CQRS.Commands.ActivityCommands;
